### ISSUE TITLE
odd server crashes in 1.1

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/Performant#1]
have these been fixed?

http://paste.ubuntu.com/p/pS6gtTYThG/
http://paste.ubuntu.com/p/bNXv76MMvR/

**Comment by someaddons** [comment]
hm this doesnt seem to be related to this mod, been reported a few times over at random patches/other places before this existed.
https://github.com/TheRandomLabs/RandomPatches/issues/59
https://github.com/CyclopsMC/EverlastingAbilities/issues/132
https://www.minecraftforge.net/forum/topic/76145-forge-281x-causing-crash-when-killing-zombies-while-invisible/

That said I could probably patch up the goal so that this crash isnt possible anymore

**Comment by kreezxil** [comment]
that would be great because then at least your mod won't come up in the
trace.

**Comment by someaddons** [comment]
https://www.curseforge.com/minecraft/mc-mods/performant/files 1.4 has the fixed version of the goal, should no longer crash at that point. (If my customizations cause an issue you can disable them in the configs)

**Comment by someaddons** [comment]
version 1.3 I meant :D
