### ISSUE TITLE
Incompatible to Dynamic Surroundings, probably caused by Mixin

### ISSUE THREAD

**Issue by ChromaPIE** [ldtteam/Performant#43]
**Describe the bug**
Already post an issue to the repository of DS: https://github.com/OreCruncher/DynamicSurroundings/issues/570, followed what the author suggested and when removed only Performant, the game successfully launched. So I'm wondering if Performant is not using Mixin 0.8 for now, which is bringing incompatible.

**To Reproduce**
1. Contain both Dynamic Surroundings and Performant in the same pack
2. Launch the game
3. Crash on startup

**Expected behavior**
Kill the incompatibility of both mods

** Mod version **
Performant 1.10

** Logs **
https://gist.github.com/ChromaPIE/8374f8771fe7d73e877c7344f4b17e1f

**Comment by someaddons** [comment]
performant is using mixin 0.8 and the 1.12 version is no longer getting updates

**Comment by Tommsy64** [comment]
I fixed this same issue by making sure Mixins v8.1 load before Performant. (Mixins v8.0 did not work for some reason.) I did this by renaming a mod that I knew used Mixins v8.1 to begin with an underscore, thus moving it to the very top of the mod list.

**Comment by 0H4rl3qu1n0** [comment]
Tommsy64 how do i find out which mods use mixins 8.1

**Comment by ZacDelves** [comment]
@Tommsy64 i would also like to know how to find this out :o

**Comment by Dimentive** [comment]
Why isn’t the 1.12.2 version of Performant getting updates? That’s a shame.

**Comment by ZacDelves** [comment]
> Why isn’t the 1.12.2 version of Performant getting updates? That’s a shame.

Exactly. 90% of mods downloaded are 1.12.2 versions, just look at minecolonies page, the ratios are atrocious....look to modpacks like rotn and the potential still on 1.12.2 is enormous.

Nevertheless, @Tommsy64 where should i look/what should i look for to find out which mod out of 200+ use mixins 0.8, so that i could do what you described?

**Comment by ZacDelves** [comment]
@someaddons might you have any clue about how tommysy64 found what mod he needed to change the "load order" of via the underscore putting it first in line?

**Comment by someaddons** [comment]
1.12 is a dying version and I got limited time... this is a 100% unpaid freetime thing so I rather spent time developing newer versions.  Beside performant has 60k 1.12 downloads and 1.1kk 1.15

**Comment by Dimentive** [comment]
I understand. I do, personally, wish that the modding community wouldn’t move on so fast because it creates so much discrepancy. I think that we should’ve stuck with 1.12.2 longer because it was such a stable version in terms of mods: so many mods that were frequently updated. We’re just moving on too fast to new versions, in my opinion, which creates a lot of problems: Mods for 1.12.2 are updated for newer versions, and the 1.12.2 versions of mods are abandoned. Then, there are new mods for the newer versions that aren’t available for 1.12.2 at all, but then there are also a lot of great mods for 1.12.2 that haven’t yet been updated to the latest versions, so this means that whichever version you play, you’re going to be missing out on a lot, and there’s nothing to do about that.

Of course, that doesn’t fall on you in the slightest. I understand the difficulty in maintaining a mod for multiple versions of the game, and it’s better for you to work on improving the mod for only one version rather than having to make sure each update works for both 1.12.2 and 1.15.2. It’s not your fault that the modding community moves on too fast; I just wish it didn’t. I think it’d be better for players—since we’d have all the mods for one version rather than some mods only being available for newer versions of the game and mods for the older versions being abandoned—and better for the mod developers, since they wouldn’t have to focus on updating their mods to the latest versions all the time.

Also, on an unrelated note, I’m kind of curious as to why you’re listed as a contributor on GitHub even though you’re the owner and sole developer of the mod, according to the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/performant).

(Also also, when you say “1.1kk,” do you mean 1.1m?)

**Comment by ZacDelves** [comment]
@Tommsy64 @someaddons pardon me. This may still be an issue for some but i only assumed it had issues with dynamic surroundings based on what I've seen online. This must have been resolved in an update for something, as, my game is running fine with both, no workarounds needed. Cheers : )
